(()=>{'use strict';
const sb=window.CrudeForceReportsAPI?.sb,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),fmt=v=>v?new Date(v).toLocaleString():'—';
const TYPES=[['production','Production Report'],['operations','Operations Summary'],['workovers','Workover Report'],['acid','Acid Job After-Action Report'],['chemical','Chemical Treatment Report'],['wellmaster','Well Master Report'],['contractors','Contractor List Report']];
let state={type:'production',period:'weekly',from:'',to:'',lease:'',well:''},refs={leases:[],wells:[]};
const ymd=d=>{const x=new Date(d);return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')};
function range(p){const d=new Date();d.setHours(12,0,0,0);let a=new Date(d),b=new Date(d);if(p==='weekly'){const day=(d.getDay()+6)%7;a.setDate(d.getDate()-day);b=new Date(a);b.setDate(a.getDate()+6)}else if(p==='monthly'){a=new Date(d.getFullYear(),d.getMonth(),1,12);b=new Date(d.getFullYear(),d.getMonth()+1,0,12)}else if(p==='yearly'){a=new Date(d.getFullYear(),0,1,12);b=new Date(d.getFullYear(),11,31,12)}return{from:ymd(a),to:ymd(b)}}
async function loadRefs(){const [l,w]=await Promise.all([sb.from('leases').select('id,name').order('name'),sb.from('wells').select('id,lease_id,well_number,source_well_name').order('well_number')]);if(l.error)throw l.error;if(w.error)throw w.error;refs={leases:l.data||[],wells:w.data||[]}}
const ln=id=>refs.leases.find(x=>x.id===id)?.name||'', wn=id=>{const w=refs.wells.find(x=>x.id===id);return w?(w.source_well_name||((ln(w.lease_id)?ln(w.lease_id)+' ':'')+(w.well_number||''))):''};
function controls(){if(state.period!=='custom')Object.assign(state,range(state.period));return '<div class="formgrid"><div class="field"><label>Report Type</label><select id="rv2type">'+TYPES.map(x=>'<option value="'+x[0]+'" '+(state.type===x[0]?'selected':'')+'>'+x[1]+'</option>').join('')+'</select></div><div class="field"><label>Period</label><select id="rv2period">'+['daily','weekly','monthly','yearly','custom'].map(x=>'<option '+(state.period===x?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>From</label><input id="rv2from" type="date" value="'+state.from+'"></div><div class="field"><label>To</label><input id="rv2to" type="date" value="'+state.to+'"></div><div class="field"><label>Lease</label><select id="rv2lease"><option value="">All</option>'+refs.leases.map(x=>'<option value="'+x.id+'" '+(state.lease===x.id?'selected':'')+'>'+esc(x.name)+'</option>').join('')+'</select></div><div class="field"><label>Well</label><select id="rv2well"><option value="">All</option>'+refs.wells.filter(w=>!state.lease||w.lease_id===state.lease).map(w=>'<option value="'+w.id+'" '+(state.well===w.id?'selected':'')+'>'+esc(wn(w.id))+'</option>').join('')+'</select></div></div>'}
async function home(){try{await loadRefs();if(!state.from)Object.assign(state,range(state.period));$('#content').innerHTML='<div class="panel"><h2>Reports</h2><div class="notice">Standalone Reports v2. Select any report, period, lease, or well.</div>'+controls()+'<div class="toolbar" style="margin-top:12px"><button class="btn primary" id="rv2run">View Report</button></div><div id="rv2out"></div></div>';const sync=()=>{state.type=$('#rv2type').value;state.period=$('#rv2period').value;state.from=$('#rv2from').value;state.to=$('#rv2to').value;state.lease=$('#rv2lease').value;state.well=$('#rv2well').value};$('#rv2period').onchange=()=>{sync();if(state.period!=='custom')Object.assign(state,range(state.period));home()};$('#rv2lease').onchange=()=>{sync();home()};$('#rv2run').onclick=()=>{sync();run()}}catch(e){$('#content').innerHTML='<div class="panel"><div class="notice">'+esc(e.message||e)+'</div></div>'}}
async function fetchRows(){let table,col;if(state.type==='workovers'){table='workovers';col='rig_move_in_at'}else if(state.type==='acid'){table='acid_jobs';col='started_at'}else if(state.type==='chemical'){table='chemical_treatments';col='treatment_at'}else if(state.type==='production'){table='oil_sales_pickups';col='picked_up_at'}else if(state.type==='operations'){table='status_events';col='occurred_at'}else if(state.type==='wellmaster'){table='wells';col='created_at'}else{table='contractors';col='created_at'}let q=sb.from(table).select('*').order(col,{ascending:false});if(!['wellmaster','contractors'].includes(state.type))q=q.gte(col,state.from+'T00:00:00').lte(col,state.to+'T23:59:59.999');const x=await q;if(x.error)throw x.error;return x.data||[]}
async function run(){const o=$('#rv2out');o.innerHTML='<p>Loading…</p>';try{let rows=await fetchRows();rows=rows.filter(r=>!state.well||r.well_id===state.well).filter(r=>!state.lease||r.lease_id===state.lease||refs.wells.find(w=>w.id===r.well_id)?.lease_id===state.lease);const title=TYPES.find(x=>x[0]===state.type)?.[1]||'Report';o.innerHTML='<div style="margin-top:18px"><div class="toolbar"><h2 style="margin-right:auto">'+esc(title)+'</h2><button class="btn primary" onclick="window.print()">Print / Save PDF</button></div><div class="muted">'+esc(state.from)+' through '+esc(state.to)+' • '+rows.length+' record(s)</div><div class="mobilecards" style="margin-top:12px">'+(rows.length?rows.map(card).join(''):'<div class="empty">No matching records.</div>')+'</div></div>'}catch(e){o.innerHTML='<div class="notice">'+esc(e.message||e)+'</div>'}}
function card(r){let title='',sub='',body='';if(state.type==='production'){title=(r.tank_number?'Tank '+r.tank_number:'Oil Sale / Pickup');sub=fmt(r.picked_up_at||r.called_in_at);body=[r.purchaser,r.gross_bbl_hauled!=null?r.gross_bbl_hauled+' bbl':null,r.status].filter(Boolean).join(' • ')}else if(state.type==='operations'){title=wn(r.well_id)||ln(r.lease_id)||'Operations Event';sub=fmt(r.occurred_at);body=r.note||r.notes||r.status||r.event_type||''}else if(state.type==='workovers'){title=wn(r.well_id)||'Workover';sub=fmt(r.rig_move_in_at);body=r.reason_for_pulling||r.actual_findings||r.state||''}else if(state.type==='acid'){title=wn(r.well_id)||'Acid Job';sub=fmt(r.started_at||r.planned_for);body=r.treatment_objective||r.outcome||r.state||''}else if(state.type==='chemical'){title=wn(r.well_id)||ln(r.lease_id)||r.target_description||'Chemical Treatment';sub=fmt(r.treatment_at);body=[r.chemical_product,r.quantity!=null?r.quantity+' '+(r.quantity_unit||''):null,r.duration_minutes!=null?r.duration_minutes+' min':null].filter(Boolean).join(' • ')}else if(state.type==='wellmaster'){title=wn(r.id)||r.well_number||'Well';sub=r.current_status||'';body=[r.well_type,r.api_number,r.reason_down].filter(Boolean).join(' • ')}else{title=r.name||'Contractor';sub=r.status||'';body=[r.contact_name,r.phone,r.email,(r.service_categories||[]).join(', ')].filter(Boolean).join(' • ')}return '<div class="panel"><h3 style="margin:0 0 5px">'+esc(title)+'</h3><div class="muted">'+esc(sub)+'</div><div>'+esc(body)+'</div></div>'}
window.CrudeForceReportsV2={home,run};
})();